### ISSUE TITLE
Update.php removal

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/survey_server#28]
Hi @schiessle,

the `appinfo/update.php` mechanism was deprecated more than three years ago and we'll soon remove it in favor of the more robust and versatile repair steps. Please use a `pre-migration` or `post-migration` step for that code.

:v:

**Comment by ChristophWurst** [comment]
Same applies to the `install.php` in fact. You can use an `install` repair step for this.

**Comment by MorrisJobke** [comment]
> Please use a `pre-migration` or `post-migration` step for that code.

Not needed as it only adds the background job which has it's own entries in the info.xml.

**Comment by ChristophWurst** [comment]
I didn't look at the code tbh.

So we can just drop the file?

**Comment by MorrisJobke** [comment]
> So we can just drop the file?

and add the entry to the info.xml, yes

**Comment by ChristophWurst** [comment]
There is no entry in https://github.com/nextcloud/survey_server/blob/master/appinfo/info.xml :thinking:

**Comment by ChristophWurst** [comment]
PR at https://github.com/nextcloud/survey_server/pull/29
